#ifndef _TNEF_ERRORS_
#define _TNEF_ERRORS_


#define YTNEF_CANNOT_INIT_DATA -1
#define YTNEF_NOT_TNEF_STREAM  -2
#define YTNEF_ERROR_READING_DATA -3
#define YTNEF_NO_KEY -4
#define YTNEF_BAD_CHECKSUM -5
#define YTNEF_ERROR_IN_HANDLER -6
#define YTNEF_UNKNOWN_PROPERTY -7
#define YTNEF_INCORRECT_SETUP -8


#endif

